name: CI build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Check the console scripts interface
      run: |
        pipenv run seleniumbase
        pipenv run sbase
    - name: Install chromedriver
      run: |
        pipenv run seleniumbase install chromedriver
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pipenv run pytest nothing.py
    - name: Run Linter
      run: |
        pipenv run flake8 specs/
    - name: Run File Formatter
      run: |
        pipenv run black --check specs/
    - name: Run tests on Browserstack
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        pipenv run pytest specs/test_home.py spec/test_upload.py -n=4 --browser=remote --server=${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}@hub.browserstack.com --cap_file=config/bs_caps.json --headless -v -s --dashboard --html=report/report.html
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: HTML Report
        path: report/